// This file was generated by typhen-api

using TyphenApi.Type;

namespace TyphenApi
{
    public interface IWebSocketApi
    {
        TyphenApi.TypeBase DispatchMessageEvent(int messageType, byte[] messageData);
    }
}
