// This file was generated by typhen-api

using System.Collections;
using System.Collections.Generic;

namespace TyphenApi
{
    public class SynchronizedFunctionCaller
    {
        public delegate void Function();

        List<Function> reservedFunctions = new List<Function>();

        public void ReserveCall(Function function)
        {
            lock (((ICollection)reservedFunctions).SyncRoot)
            {
                reservedFunctions.Add(function);
            }
        }

        public void Call()
        {
            Function[] functions;

            lock (((ICollection)reservedFunctions).SyncRoot)
            {
                functions = reservedFunctions.ToArray();
                reservedFunctions.Clear();
            }

            foreach (var function in functions)
            {
                function();
            }
        }
    }
}
