// This file was generated by typhen-api

package submarine

import (
	"app/typhen_api/core"
	_submarine_battle "app/typhen_api/messagedispatcher/submarine/battle"
)

// MessageDispatcher handles raw binary messages, and dispatches messages to sub handlers.
type MessageDispatcher struct {
	serializer   *typhenapi.Serializer
	errorHandler func([]byte, error)
	Battle       *_submarine_battle.MessageDispatcher
}

// New creates a MessageDispatcher.
func New(serializer *typhenapi.Serializer, errorHandler func([]byte, error)) *MessageDispatcher {
	d := &MessageDispatcher{}
	d.serializer = serializer
	d.errorHandler = errorHandler
	d.Battle = _submarine_battle.New(serializer, errorHandler)
	return d
}

// HandleMessage handles a binary message.
func (d *MessageDispatcher) HandleMessage(data []byte) {
	d.Battle.HandleMessage(data)

}
