source 'https://rubygems.org'

gem 'rails', '5.0.0'
gem 'mysql2'
gem 'sdoc', '~> 0.4.0', group: :doc

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'virtus'
gem 'config'
gem 'hashie'
gem 'baby_squeel'

group :development do
  gem 'bullet'
end

group :development, :test do
  gem 'spring'

  gem 'pry-rails'
  gem 'guard-rspec', require: false
  gem 'rspec-rails', '~> 3.0'
  gem 'factory_girl_rails'
  gem 'shoulda-matchers'
  gem 'rspec-its'

  gem 'hirb'
  gem 'hirb-unicode'

  gem 'timecop'
  gem 'database_cleaner'
  gem 'faker'
  gem 'tapp-awesome_print'
  gem 'annotate', '~> 2.6.6'
end

