include FileUtils

task default: :test

desc 'Make a release binary'
task :dist => [:restore_dependencies, :generate, :test, :build]

desc 'Initialize the project tools'
task :init do
  sh 'go get github.com/FiloSottile/gvt'
  sh 'go get github.com/clipperhouse/gen'
  sh 'go get github.com/shiwano/genem'
  sh 'go get golang.org/x/tools/cmd/goimports'
end

desc 'Build a binary'
task :build do
  sh 'go build'
end

namespace :build do
  desc 'Build all binaries'
  task :all => [:build, 'build:debug']

  desc 'Build a debug binary'
  task :debug do
    sh 'go build -tags=debug -o ./battle_debug'
  end
end

desc 'Run all tests'
task :test do
  sh 'go test $(go list ./... | grep -v /vendor/)'
end

desc 'Restore dependencies'
task :restore_dependencies do
  sh 'gvt restore'
end

desc 'Generate code'
task :generate do
  sh 'go generate $(go list ./... | grep -v /vendor/)'
end

desc 'Apply goimport'
task :goimport do
  sh 'goimports -w $(find . -type f -name \'*.go\' -not -path "./vendor/*" -and -not -path "./lib/typhenapi/*")'
end
