include FileUtils

desc 'Run all tests'
task :test do
  sh 'SUBMARINE_ENV=test go test $(go list ./... | grep -v /vendor/)'
end

desc 'Remove cache directory'
task :remove_cache do
  rm_rf '.cache'
end
