include FileUtils

desc 'Make a release binary'
task dist: [:restore_dependencies, :test, :build]

desc 'Build a binary'
task :build do
  sh 'go build'
end

desc 'Run all tests'
task :test do
  sh 'SUBMARINE_ENV=test go test $(go list ./... | grep -v /vendor/)'
end

desc 'Remove cache directory'
task :remove_cache do
  rm_rf '.cache'
end

desc 'Restore dependencies with gvt'
task :restore_dependencies do
  sh 'go get github.com/FiloSottile/gvt && gvt restore'
end
