// This file was generated by typhen-api

using System;
using System.Text;
using Newtonsoft.Json;

namespace TyphenApi
{
    public class JSONSerializer : ISerializer, IDeserializer
    {
        public byte[] Serialize<T>(T obj)
        {
            try
            {
                var text = JsonConvert.SerializeObject(obj);
                return Encoding.UTF8.GetBytes(text);
            }
            catch (Exception e)
            {
                throw new SerializationFailureException("Failed to serialize a object to a JSON string", e);
            }
        }

        public T Deserialize<T>(byte[] bytes) where T : new()
        {
            try
            {
                var text = Encoding.UTF8.GetString(bytes);
                return JsonConvert.DeserializeObject<T>(text);
            }
            catch (Exception e)
            {
                throw new DeserializationFailureException("Failed to deserialize a object from a JSON string", e);
            }
        }
    }
}
