// This file was generated by typhen-api

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using MiniJSON;

namespace TyphenApi
{
    public class JSONSerializer : ISerializer, IDeserializer
    {
        public byte[] Serialize(object obj)
        {
            string text = string.Empty;

            if (obj != null && IsSerializableObject(obj.GetType()))
            {
                var dict = SerializeClassOrStruct(obj);
                text = Json.Serialize(dict);
            }

            return Encoding.UTF8.GetBytes(text);
        }

        public T Deserialize<T>(byte[] bytes) where T : new()
        {
            if (bytes.Length > 0)
            {
                var text = Encoding.UTF8.GetString(bytes);
                var dict = Json.Deserialize(text) as Dictionary<string, object>;
                var deserialized = DeserializeClassOrStruct(typeof(T), dict);
                return (T)deserialized;
            }
            else
            {
                return default(T);
            }
        }

        Dictionary<string, object> SerializeClassOrStruct(object obj)
        {
            var dict = new Dictionary<string, object>();

            foreach (var info in SerializationInfoUtility.FindAll(obj))
            {
                var value = info.GetValue(obj);
                var valueType = info.ValueType;

                if (value == null)
                {
                    if (info.IsOptional)
                    {
                        continue;
                    }
                    else
                    {
                        var message = string.Format("{0}.{1} is not allowed to be null.", obj.GetType().FullName, info.PropertyName);
                        throw new NoNullAllowedException(message);
                    }
                }

                if (IsSerializableValue(value, valueType))
                {
                    dict[info.PropertyName] = valueType.IsEnum ? (long)value : value;
                }
                else if (IsSerializableObject(valueType))
                {
                    dict[info.PropertyName] = SerializeClassOrStruct(value);
                }
                else
                {
                    var message = string.Format("Failed to serialize {0} ({1}) to {2}.{3}", value, valueType, obj.GetType().FullName, info.PropertyName);
                    throw new SerializeFailedException(message);
                }
            }
            return dict;
        }

        object DeserializeClassOrStruct(System.Type objType, Dictionary<string, object> dict)
        {
            object obj = Activator.CreateInstance(objType);

            foreach (var info in SerializationInfoUtility.FindAll(objType))
            {
                var value = dict[info.PropertyName];
                var valueType = info.ValueType;

                if (value == null)
                {
                    if (info.IsOptional)
                    {
                        continue;
                    }
                    else
                    {
                        var message = string.Format("{0}.{1} is not allowed to be null.", objType.FullName, info.PropertyName);
                        throw new NoNullAllowedException(message);
                    }
                }

                if (IsSerializableValue(value, valueType))
                {
                    info.SetValue(obj, value);
                }
                else if (IsSerializableObject(valueType))
                {
                    var parsed = DeserializeClassOrStruct(valueType, (Dictionary<string, object>)value);
                    info.SetValue(obj, parsed);
                }
                else
                {
                    var message = string.Format("Failed to deserialize {0} ({1}) to {2}.{3}", value, valueType, objType.FullName, info.PropertyName);
                    throw new DeserializeFailedException(message);
                }
            }
            return obj;
        }

        bool IsIDictionaryImplementation(System.Type type)
        {
            return typeof(IDictionary).IsAssignableFrom(type);
        }

        bool IsStruct(System.Type type)
        {
            return type.IsValueType && !type.IsEnum;
        }

        bool IsSerializableObject(System.Type type)
        {
            return type.IsClass || IsStruct(type);
        }

        bool IsSerializableValue(object value, System.Type valueType)
        {
            return valueType.IsPrimitive || valueType.IsEnum ||
                value is string || value is IList ||
                (value is IDictionary && IsIDictionaryImplementation(valueType));
        }
    }
}
