// This file was generated by typhen-api

using System;

namespace TyphenApi
{
    public abstract class SerializationException : Exception
    {
        protected SerializationException(string message, Exception innerException = null) : base(message, innerException) {}
    }

    public class SerializationFailureException : SerializationException
    {
        public SerializationFailureException(string message, Exception innerException = null) : base(message, innerException) {}
    }

    public class DeserializationFailureException : SerializationException
    {
        public DeserializationFailureException(string message, Exception innerException = null) : base(message, innerException) {}
    }
}
