# This file was generated by typhen-api

Rails.application.routes.draw do

  post 'ping' => 'ping#service'
  post 'sign_up' => 'sign_up#service'
  post 'login' => 'login#service'
  post 'find_user' => 'find_user#service'

end
