// This file was generated by typhen-api

package battle

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// ActorRequestObject is a kind of TyphenAPI type.
type ActorRequestObject struct {
	Type *ActorType `codec:"type"`
}

// Coerce the fields.
func (t *ActorRequestObject) Coerce() error {
	if t.Type == nil {
		return errors.New("Type should not be empty")
	}
	if err := t.Type.Coerce(); err != nil {
		return err
	}
	return nil
}

// Bytes creates the byte array.
func (t *ActorRequestObject) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
