// This file was generated by typhen-api

package battle

import (
	"errors"
)

type ActorType int

func (i ActorType) String() string {
	switch i {
	case ActorType_Submarine:
		return "Submarine"
	case ActorType_Torpedo:
		return "Torpedo"
	case ActorType_Decoy:
		return "Decoy"
	case ActorType_Lookout:
		return "Lookout"
	}
	return ""
}

func (i ActorType) Coerce() error {
	switch i {
	case ActorType_Submarine:
		return nil
	case ActorType_Torpedo:
		return nil
	case ActorType_Decoy:
		return nil
	case ActorType_Lookout:
		return nil
	}
	return errors.New("No ActorType")
}

const (
	ActorType_Submarine ActorType = 0
	ActorType_Torpedo   ActorType = 1
	ActorType_Decoy     ActorType = 2
	ActorType_Lookout   ActorType = 3
)
