// This file was generated by typhen-api

package battle

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// Destruction is a kind of TyphenAPI type.
type Destruction struct {
	ActorId int64 `codec:"actor_id"`
}

// Coerce the fields.
func (t *Destruction) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *Destruction) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
