// This file was generated by typhen-api

package battle

import (
	"errors"
)

var _ = errors.New

// FindRoomObject is kind of a TyphenAPI type.
type FindRoomObject struct {
	Room *Room `codec:"room"`
}

// Coerce the fields.
func (t *FindRoomObject) Coerce() error {
	return nil
}
