// This file was generated by typhen-api

package battle

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// MeshData is a kind of TyphenAPI type.
type MeshData struct {
	Vertices  []*Point `codec:"vertices"`
	Triangles []int64  `codec:"triangles"`
}

// Coerce the fields.
func (t *MeshData) Coerce() error {
	if t.Vertices == nil {
		return errors.New("Vertices should not be empty")
	}
	if t.Triangles == nil {
		return errors.New("Triangles should not be empty")
	}
	return nil
}

// Bytes creates the byte array.
func (t *MeshData) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
