// This file was generated by typhen-api

package battle

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// Movement is a kind of TyphenAPI type.
type Movement struct {
	ActorId  int64   `codec:"actor_id"`
	Position *Vector `codec:"position"`
	Velocity *Vector `codec:"velocity"`
	MovedAt  int64   `codec:"moved_at"`
}

// Coerce the fields.
func (t *Movement) Coerce() error {
	if t.Position == nil {
		return errors.New("Position should not be empty")
	}
	if t.Velocity == nil {
		return errors.New("Velocity should not be empty")
	}
	return nil
}

// Bytes creates the byte array.
func (t *Movement) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
