// This file was generated by typhen-api

package battle

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// Point is a kind of TyphenAPI type.
type Point struct {
	X float64 `codec:"x"`
	Y float64 `codec:"y"`
}

// Coerce the fields.
func (t *Point) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *Point) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
