// This file was generated by typhen-api

package battle

import (
	submarine "app/typhenapi/type/submarine"
	"errors"
)

var _ = errors.New

// RoomMember is kind of a TyphenAPI type.
type RoomMember struct {
	RoomKey string          `codec:"room_key"`
	User    *submarine.User `codec:"user"`
}

// Coerce the fields.
func (t *RoomMember) Coerce() error {
	if t.User == nil {
		return errors.New("User should not be empty")
	}
	return nil
}
