// This file was generated by typhen-api

package battle

import (
	"errors"
)

var _ = errors.New

// RoomMember is kind of a TyphenAPI type.
type RoomMember struct {
	RoomKey string `codec:"room_key"`
	Name    string `codec:"name"`
}

// Coerce the fields.
func (t *RoomMember) Coerce() error {
	return nil
}
