// This file was generated by typhen-api

package battle

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// Speed is a kind of TyphenAPI type.
type Speed struct {
	Max           float64 `codec:"max"`
	AcceleratedAt int64   `codec:"accelerated_at"`
	Duration      int64   `codec:"duration"`
}

// Coerce the fields.
func (t *Speed) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *Speed) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
