// This file was generated by typhen-api

package battle

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// StartRequestObject is a kind of TyphenAPI type.
type StartRequestObject struct {
}

// Coerce the fields.
func (t *StartRequestObject) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *StartRequestObject) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
