// This file was generated by typhen-api

package battle

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// TurnRequestObject is a kind of TyphenAPI type.
type TurnRequestObject struct {
	Direction *Vector `codec:"direction"`
}

// Coerce the fields.
func (t *TurnRequestObject) Coerce() error {
	if t.Direction == nil {
		return errors.New("Direction should not be empty")
	}
	return nil
}

// Bytes creates the byte array.
func (t *TurnRequestObject) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
