// This file was generated by typhen-api

namespace TyphenApi
{
    public interface IWebApiController<ErrorT> where ErrorT : TypeBase
    {
        IWebApiRequestSender RequestSender { get; }
        ISerializer RequestSerializer { get; }
        IDeserializer ResponseDeserializer { get; }

        void OnBeforeRequestSend(IWebApiRequest request);
        void OnRequestError(IWebApiRequest request, WebApiError<ErrorT> error);
        void OnRequestSuccess(IWebApiRequest request, IWebApiResponse response);
    }
}
