// This file was generated by typhen-api

namespace TyphenApi
{
    public interface IWebApiController<ErrorT> where ErrorT : TypeBase
    {
        IWebApiRequestSender RequestSender { get; }
        ISerializer Serializer { get; }
        IDeserializer Deserializer { get; }

        void OnBeforeRequestSend(IWebApiRequest request);
        void OnRequestError(WebApiError<ErrorT> error);
        void OnRequestSuccess(IWebApiRequest request, IWebApiResponse response);
    }
}
