// This file was generated by typhen-api

using System;

namespace TyphenApi
{
    public abstract class WebApiBase<ErrorT> where ErrorT : TypeBase
    {
        public Uri BaseUri { get; private set; }
        public IWebApiController<ErrorT> Controller { get; protected set; }

        protected WebApiBase(string baseUri)
        {
            BaseUri = new Uri(baseUri);
        }

        public WebApiError<ErrorT> Error(Exception error)
        {
            return error as WebApiError<ErrorT>;
        }
    }
}
