// This file was generated by typhen-api

using System;
using System.Collections;
using System.Collections.Generic;

namespace TyphenApi
{
    public enum HttpMethod
    {
        Get,
        Post,
        Put,
        Delete
    }

    public interface IWebApiRequest
    {
        Uri Uri { get; set; }
        HttpMethod Method { get; set; }
        Dictionary<string, string> Headers { get; set; }
        bool NoAuthenticationRequired { get; set; }
        TypeBase Body { get; }
        byte[] BodyBytes { get; }
        bool IsSending { get; }

        void OnSendComplete(Dictionary<string, string> headers, byte[] bytes, string errorText);
    }

    public partial class WebApiRequest<ResponseT, ErrorT> : IWebApiRequest
        where ResponseT : TypeBase, new()
        where ErrorT : TypeBase, new()
    {
        readonly IWebApi<ErrorT> api;
        IEnumerator sendingRoutine;

        public Uri Uri { get; set; }
        public HttpMethod Method { get; set; }
        public Dictionary<string, string> Headers { get; set; }
        public bool NoAuthenticationRequired { get; set; }
        public TypeBase Body { get; set; }
        public byte[] BodyBytes { get { return api.RequestSerializer.Serialize(Body); } }
        public bool IsSending { get { return sendingRoutine != null; } }

        public WebApiResponse<ResponseT> Response { get; private set; }
        public WebApiError<ErrorT> Error { get; private set; }

        public WebApiRequest(IWebApi<ErrorT> api)
        {
            Headers = new Dictionary<string, string>();
            this.api = api;
        }

        public WebApiRequest<ResponseT, ErrorT> Set(string headerName, string headerValue)
        {
            Headers[headerName] = headerValue;
            return this;
        }

        public IEnumerator SendAsync()
        {
            if (IsSending)
            {
                return sendingRoutine;
            }
            else
            {
                api.OnBeforeRequestSend(this);
                sendingRoutine = api.RequestSender.Send(this);
                return sendingRoutine;
            }
        }

        public void OnSendComplete(Dictionary<string, string> headers, byte[] bytes, string errorText)
        {
            sendingRoutine = null;
            Response = null;
            Error = null;

            if (string.IsNullOrEmpty(errorText))
            {
                try
                {
                    var response = api.ResponseDeserializer.Deserialize<ResponseT>(bytes);
                    Response = new WebApiResponse<ResponseT>(headers, response);
                }
                catch (SerializationException)
                {
                    Error = new WebApiError<ErrorT>(headers, null, bytes, "Failed to deserialize a response");
                }
            }
            else
            {
                try
                {
                    var error = api.ResponseDeserializer.Deserialize<ErrorT>(bytes);
                    Error = new WebApiError<ErrorT>(headers, error, bytes, errorText);
                }
                catch (SerializationException)
                {
                    Error = new WebApiError<ErrorT>(headers, null, bytes, errorText);
                }
            }

            if (Error == null)
            {
                api.OnRequestSuccess(this, Response);
            }
            else
            {
                api.OnRequestError(this, Error);
            }
        }
    }
}
