// This file was generated by typhen-api

using System.Collections.Generic;

namespace TyphenApi
{
    public interface IWebApiResponse
    {
        Dictionary<string,string> Headers { get; }
        IType Body { get; }
    }

    public class WebApiResponse<T> : IWebApiResponse where T : IType
    {
        public Dictionary<string, string> Headers { get; private set; }
        public IType Body { get { return Data; } }

        public T Data { get; private set; }

        public WebApiResponse(Dictionary<string, string> headers, T response)
        {
            Headers = headers;
            Data = response;
        }
    }
}
