// This file was generated by typhen-api

package submarine

import (
	"app/typhenapi/core"
	"errors"
	"fmt"
	"net/url"
)

var _ = errors.New

type JoinIntoRoomRequestBody struct {
	RoomId int64 `codec:"room_id"`
}

// Coerce the fields.
func (t *JoinIntoRoomRequestBody) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *JoinIntoRoomRequestBody) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}

// QueryString returns the query string.
func (t *JoinIntoRoomRequestBody) QueryString() string {
	queryString := fmt.Sprintf("room_id=%v", t.RoomId)
	return url.QueryEscape(queryString)
}
