// This file was generated by typhen-api

package submarine

import (
	"app/typhenapi/core"
	"errors"
	"fmt"
	"net/url"
)

var _ = errors.New

type LoginRequestBody struct {
	AuthToken string `codec:"auth_token"`
}

// Coerce the fields.
func (t *LoginRequestBody) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *LoginRequestBody) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}

// QueryString returns the query string.
func (t *LoginRequestBody) QueryString() string {
	queryString := fmt.Sprintf("auth_token=%v", t.AuthToken)
	return url.QueryEscape(queryString)
}
