// This file was generated by typhen-api

package submarine

import (
	"app/typhenapi/core"
	"errors"
	"fmt"
	"net/url"
)

var _ = errors.New

type PingRequestBody struct {
	Message string `codec:"message"`
}

// Coerce the fields.
func (t *PingRequestBody) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *PingRequestBody) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}

// QueryString returns the query string.
func (t *PingRequestBody) QueryString() string {
	queryString := fmt.Sprintf("message=%v", t.Message)
	return url.QueryEscape(queryString)
}
