// This file was generated by typhen-api

package submarine

import (
	"app/typhenapi/core"
	"errors"
	"fmt"
	"net/url"
)

var _ = errors.New

type SignUpRequestBody struct {
	Name     string `codec:"name"`
	Password string `codec:"password"`
}

// Coerce the fields.
func (t *SignUpRequestBody) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *SignUpRequestBody) Bytes(serializer *typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}

// QueryString returns the query string.
func (t *SignUpRequestBody) QueryString() string {
	queryString := fmt.Sprintf("name=%v&password=%v", t.Name, t.Password)
	return url.QueryEscape(queryString)
}
