// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// Error is kind of a TyphenAPI type.
type Error struct {
	Code    int    `codec:"code"`
	Name    string `codec:"name"`
	Message string `codec:"message"`
}

// Coerce the fields.
func (t *Error) Coerce() error {
	return nil
}
