// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// LoginObject is kind of a TyphenAPI type.
type LoginObject struct {
	User *User `codec:"user"`
}

// Coerce the fields.
func (t *LoginObject) Coerce() error {
	if t.User == nil {
		return errors.New("User should not be empty")
	}
	return nil
}
