# This file was generated by typhen-api

module TyphenApi::Controller::Submarine::Battle
  module FindRoomMember
    extend ActiveSupport::Concern

    class RequestType
      include Virtus.model(:strict => true)

      attribute :room_key, String, :required => true
    end

    ResponseType = TyphenApi::Model::Submarine::Battle::FindRoomMemberObject
    ErrorType = TyphenApi::Model::Submarine::Error

    def no_authentication_required?
      true
    end
  end
end
