# This file was generated by typhen-api

module TyphenApi::Model::Submarine
  class GetRoomsObject
    include Virtus.model(:strict => true)

    attribute :rooms, Array[TyphenApi::Model::Submarine::Room], :required => true
  end
end
