# This file was generated by typhen-api

module TyphenApi::Model::Submarine
  class LoggedInUser
    include Virtus.model(:strict => true)

    attribute :joined_room, TyphenApi::Model::Submarine::JoinedRoom, :required => false
    attribute :id, Integer, :required => true
    attribute :name, String, :required => true
  end
end
