# This file was generated by typhen-api

module TyphenApi::Model::Submarine
  class Room
    include Virtus.model(:strict => true)

    attribute :id, Integer, :required => true
    attribute :members, Array[TyphenApi::Model::Submarine::User], :required => true
    attribute :bots, Array[TyphenApi::Model::Submarine::Bot], :required => false
  end
end
