# This file was generated by typhen-api

module TyphenApi::Model::Submarine
  class SignUpObject
    include Virtus.model(:strict => true)

    attribute :user, TyphenApi::Model::Submarine::LoggedInUser, :required => true
    attribute :auth_token, String, :required => true
    attribute :access_token, String, :required => true
  end
end
