// This file was generated by typhen-api

package messagedispatcher

import (
	"app/typhen_api/core"
	"app/typhen_api/message_dispatcher/submarine"
)

// MessageDispatcher handles raw binary messages, and dispatches messages to sub handlers.
type MessageDispatcher struct {
	serializer   *typhenapi.Serializer
	errorHandler func([]byte, error)
	Submarine    *submarine.MessageDispatcher
}

// New creates a MessageDispatcher.
func New(serializer *typhenapi.Serializer, errorHandler func([]byte, error)) *MessageDispatcher {
	d := &MessageDispatcher{}
	d.serializer = serializer
	d.errorHandler = errorHandler
	d.Submarine = submarine.New(serializer, errorHandler)
	return d
}

// HandleMessage handles a binary message.
func (d *MessageDispatcher) HandleMessage(data []byte) {
	d.Submarine.HandleMessage(data)
}
