# This file was generated by typhen-api

module TyphenApi::Controller::Submarine
  module FindUser
    extend ActiveSupport::Concern

    class RequestType
      include Virtus.model(:strict => true)

      attribute :name, String, :required => true
    end

    ResponseType = TyphenApi::Model::Submarine::FindUserObject
    ErrorType = TyphenApi::Model::Submarine::Error

    def no_authentication_required?
      false
    end
  end
end
