# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Configuration
  class Client
    include Virtus.model(:strict => true)

    attribute :version, String, :required => true
    attribute :api_server_base_uri, String, :required => true
  end
end
