# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Configuration
  class ServerDatabaseObject
    include Virtus.model(:strict => true)

    attribute :host, String, :required => true
    attribute :port, Integer, :required => true
    attribute :user, String, :required => true
    attribute :password, String, :required => true
  end
end
