// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Actor

package scene

import "errors"

// Sort implementation is a modification of http://golang.org/pkg/sort/#Sort
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found at http://golang.org/LICENSE.

// ActorSlice is a slice of type Actor. Use it where you would use []Actor.
type ActorSlice []Actor

// All verifies that all elements of ActorSlice return true for the passed func. See: http://clipperhouse.github.io/gen/#All
func (rcv ActorSlice) All(fn func(Actor) bool) bool {
	for _, v := range rcv {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Any verifies that one or more elements of ActorSlice return true for the passed func. See: http://clipperhouse.github.io/gen/#Any
func (rcv ActorSlice) Any(fn func(Actor) bool) bool {
	for _, v := range rcv {
		if fn(v) {
			return true
		}
	}
	return false
}

// First returns the first element that returns true for the passed func. Returns error if no elements return true. See: http://clipperhouse.github.io/gen/#First
func (rcv ActorSlice) First(fn func(Actor) bool) (result Actor, err error) {
	for _, v := range rcv {
		if fn(v) {
			result = v
			return
		}
	}
	err = errors.New("no ActorSlice elements return true for passed func")
	return
}

// MaxBy returns an element of ActorSlice containing the maximum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally maximal, the last such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MaxBy
func (rcv ActorSlice) MaxBy(less func(Actor, Actor) bool) (result Actor, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the MaxBy of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if rcv[i] != rcv[m] && !less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// MinBy returns an element of ActorSlice containing the minimum value, when compared to other elements using a passed func defining ‘less’. In the case of multiple items being equally minimal, the first such element is returned. Returns error if no elements. See: http://clipperhouse.github.io/gen/#MinBy
func (rcv ActorSlice) MinBy(less func(Actor, Actor) bool) (result Actor, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine the Min of an empty slice")
		return
	}
	m := 0
	for i := 1; i < l; i++ {
		if less(rcv[i], rcv[m]) {
			m = i
		}
	}
	result = rcv[m]
	return
}

// SortBy returns a new ordered ActorSlice, determined by a func defining ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv ActorSlice) SortBy(less func(Actor, Actor) bool) ActorSlice {
	result := make(ActorSlice, len(rcv))
	copy(result, rcv)
	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(result)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	quickSortActorSlice(result, less, 0, n, maxDepth)
	return result
}

// Where returns a new ActorSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv ActorSlice) Where(fn func(Actor) bool) (result ActorSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// Count gives the number elements of ActorSlice that return true for the passed func. See: http://clipperhouse.github.io/gen/#Count
func (rcv ActorSlice) Count(fn func(Actor) bool) (result int) {
	for _, v := range rcv {
		if fn(v) {
			result++
		}
	}
	return
}

// GroupByString groups elements into a map keyed by string. See: http://clipperhouse.github.io/gen/#GroupBy
func (rcv ActorSlice) GroupByString(fn func(Actor) string) map[string]ActorSlice {
	result := make(map[string]ActorSlice)
	for _, v := range rcv {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}

// GroupByPlayer groups elements into a map keyed by *Player. See: http://clipperhouse.github.io/gen/#GroupBy
func (rcv ActorSlice) GroupByPlayer(fn func(Actor) *Player) map[*Player]ActorSlice {
	result := make(map[*Player]ActorSlice)
	for _, v := range rcv {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}

// Sort implementation based on http://golang.org/pkg/sort/#Sort, see top of this file

func swapActorSlice(rcv ActorSlice, a, b int) {
	rcv[a], rcv[b] = rcv[b], rcv[a]
}

// Insertion sort
func insertionSortActorSlice(rcv ActorSlice, less func(Actor, Actor) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(rcv[j], rcv[j-1]); j-- {
			swapActorSlice(rcv, j, j-1)
		}
	}
}

// siftDown implements the heap property on rcv[lo, hi).
// first is an offset into the array where the root of the heap lies.
func siftDownActorSlice(rcv ActorSlice, less func(Actor, Actor) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(rcv[first+child], rcv[first+child+1]) {
			child++
		}
		if !less(rcv[first+root], rcv[first+child]) {
			return
		}
		swapActorSlice(rcv, first+root, first+child)
		root = child
	}
}

func heapSortActorSlice(rcv ActorSlice, less func(Actor, Actor) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a

	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		siftDownActorSlice(rcv, less, i, hi, first)
	}

	// Pop elements, largest first, into end of rcv.
	for i := hi - 1; i >= 0; i-- {
		swapActorSlice(rcv, first, first+i)
		siftDownActorSlice(rcv, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort Function, SP&E November 1993.

// medianOfThree moves the median of the three values rcv[a], rcv[b], rcv[c] into rcv[a].
func medianOfThreeActorSlice(rcv ActorSlice, less func(Actor, Actor) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(rcv[m1], rcv[m0]) {
		swapActorSlice(rcv, m1, m0)
	}
	if less(rcv[m2], rcv[m1]) {
		swapActorSlice(rcv, m2, m1)
	}
	if less(rcv[m1], rcv[m0]) {
		swapActorSlice(rcv, m1, m0)
	}
	// now rcv[m0] <= rcv[m1] <= rcv[m2]
}

func swapRangeActorSlice(rcv ActorSlice, a, b, n int) {
	for i := 0; i < n; i++ {
		swapActorSlice(rcv, a+i, b+i)
	}
}

func doPivotActorSlice(rcv ActorSlice, less func(Actor, Actor) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		medianOfThreeActorSlice(rcv, less, lo, lo+s, lo+2*s)
		medianOfThreeActorSlice(rcv, less, m, m-s, m+s)
		medianOfThreeActorSlice(rcv, less, hi-1, hi-1-s, hi-1-2*s)
	}
	medianOfThreeActorSlice(rcv, less, lo, m, hi-1)

	// Invariants are:
	//	rcv[lo] = pivot (set up by ChoosePivot)
	//	rcv[lo <= i < a] = pivot
	//	rcv[a <= i < b] < pivot
	//	rcv[b <= i < c] is unexamined
	//	rcv[c <= i < d] > pivot
	//	rcv[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(rcv[b], rcv[pivot]) { // rcv[b] < pivot
				b++
			} else if !less(rcv[pivot], rcv[b]) { // rcv[b] = pivot
				swapActorSlice(rcv, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(rcv[pivot], rcv[c-1]) { // rcv[c-1] > pivot
				c--
			} else if !less(rcv[c-1], rcv[pivot]) { // rcv[c-1] = pivot
				swapActorSlice(rcv, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// rcv[b] > pivot; rcv[c-1] < pivot
		swapActorSlice(rcv, b, c-1)
		b++
		c--
	}

	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}

	n := min(b-a, a-lo)
	swapRangeActorSlice(rcv, lo, b-n, n)

	n = min(hi-d, d-c)
	swapRangeActorSlice(rcv, c, hi-n, n)

	return lo + b - a, hi - (d - c)
}

func quickSortActorSlice(rcv ActorSlice, less func(Actor, Actor) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			heapSortActorSlice(rcv, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := doPivotActorSlice(rcv, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			quickSortActorSlice(rcv, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortActorSlice(rcv, mhi, b)
		} else {
			quickSortActorSlice(rcv, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortActorSlice(rcv, a, mlo)
		}
	}
	if b-a > 1 {
		insertionSortActorSlice(rcv, less, a, b)
	}
}
