// This file was generated by typhen-api

package submarine

import (
	"app/typhen_api/core"
	"app/typhen_api/type/submarine"
)

// MessageDispatcher handles raw binary messages, and dispatches messages to sub handlers.
type MessageDispatcher struct {
	serializer   *typhenapi.Serializer
	errorHandler func([]byte, error)
	PingMessage  func(ping *submarine.PingMessage)
}

// New creates a MessageDispatcher.
func New(serializer *typhenapi.Serializer, errorHandler func([]byte, error)) *MessageDispatcher {
	d := &MessageDispatcher{}
	d.serializer = serializer
	d.errorHandler = errorHandler
	return d
}

// HandleMessage handles a binary message.
func (d *MessageDispatcher) HandleMessage(data []byte) {
	message, err := typhenapi.NewMessageFromBytes(data)
	if err != nil {
		d.errorHandler(data, err)
		return
	}

	switch message.Type {
	case 1:
		typhenType := new(submarine.PingMessage)
		if err := d.serializer.Deserialize(message.Body, typhenType); err != nil {
			d.errorHandler(data, err)
			return
		}

		if err := typhenType.Coerce(); err != nil {
			d.errorHandler(data, err)
			return
		}

		if d.PingMessage != nil {
			d.PingMessage(typhenType)
		}
	}
}
