// This file was generated by typhen-api

package configuration

import (
	"errors"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi"
)

var _ = errors.New

// Client is a kind of TyphenAPI type.
type Client struct {
	Version          string `json:"version" msgpack:"version"`
	ApiServerBaseUri string `json:"api_server_base_uri" msgpack:"api_server_base_uri"`
}

// Coerce the fields.
func (t *Client) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *Client) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
