// This file was generated by typhen-api

package configuration

import (
	"errors"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi/core"
)

var _ = errors.New

// ServerDatabaseObject is a kind of TyphenAPI type.
type ServerDatabaseObject struct {
	Host     string `codec:"host"`
	Port     int64  `codec:"port"`
	User     string `codec:"user"`
	Password string `codec:"password"`
}

// Coerce the fields.
func (t *ServerDatabaseObject) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *ServerDatabaseObject) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
