# This file was generated by typhen-api

module TyphenApi::Model::Submarine
  class FindUserObject
    include Virtus.model(:strict => true)

    attribute :user, TyphenApi::Model::Submarine::User, :required => false
  end
end
