// This file was generated by typhen-api

package submarine

import (
	"errors"
	"fmt"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi"
	"net/url"
)

var _ = errors.New

type SignUpRequestBody struct {
	Name string `json:"name" msgpack:"name"`
}

// Coerce the fields.
func (t *SignUpRequestBody) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *SignUpRequestBody) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}

// QueryString returns the query string.
func (t *SignUpRequestBody) QueryString() string {
	queryString := fmt.Sprintf("name=%v", t.Name)
	return url.QueryEscape(queryString)
}
