# This file was generated by typhen-api

module TyphenApi::Controller::Submarine
  module Ping
    extend ActiveSupport::Concern

    class RequestType
      include Virtus.model(:strict => true)

      attribute :message, String, :required => true
    end

    ResponseType = TyphenApi::Model::Submarine::PingObject
    ErrorType = TyphenApi::Model::Submarine::Error

    def no_authentication_required?
      true
    end
  end
end
