// This file was generated by typhen-api

package typhenapi

// Void is a kind of TyphenAPI type.
type Void struct {
}

// Coerce the fields.
func (t *Void) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *Void) Bytes(serializer *Serializer) ([]byte, error) {
	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
