// This file was generated by typhen-api

package submarine

import (
	"errors"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi/core"
)

var _ = errors.New

// Config is a kind of TyphenAPI type.
type Config struct {
	Version          string `codec:"version"`
	ApiServerBaseUri string `codec:"api_server_base_uri"`
}

// Coerce the fields.
func (t *Config) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *Config) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
