// This file was generated by typhen-api

package submarine

import (
	"errors"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi/core"
)

var _ = errors.New

// LoginObject is a kind of TyphenAPI type.
type LoginObject struct {
	User *LoggedInUser `codec:"user"`
}

// Coerce the fields.
func (t *LoginObject) Coerce() error {
	if t.User == nil {
		return errors.New("User should not be empty")
	}
	return nil
}

// Bytes creates the byte array.
func (t *LoginObject) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
