// This file was generated by typhen-api

using System.Text;

namespace TyphenApi
{
    public abstract class TypeBase
    {
        protected static readonly JSONSerializer jsonSerializer = new JSONSerializer();
        protected static readonly QueryStringSerializer queryStringSerializer = new QueryStringSerializer();

        public override string ToString()
        {
            return ToJSON();
        }

        public string ToJSON()
        {
            return Encoding.UTF8.GetString(jsonSerializer.Serialize(this));
        }

        public string ToQueryString()
        {
            return Encoding.UTF8.GetString(queryStringSerializer.Serialize(this));
        }
    }

    public abstract class TypeBase<T> : TypeBase where T : new()
    {
        public static T FromJSON(string text)
        {
            return jsonSerializer.Deserialize<T>(Encoding.UTF8.GetBytes(text));
        }
    }
}
