// This file was generated by typhen-api

package battle

import (
	"errors"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi/core"
)

var _ = errors.New

// Actor is a kind of TyphenAPI type.
type Actor struct {
	Id        int64     `codec:"id"`
	UserId    int64     `codec:"user_id"`
	Type      ActorType `codec:"type"`
	Movement  *Movement `codec:"movement"`
	IsVisible bool      `codec:"is_visible"`
}

// Coerce the fields.
func (t *Actor) Coerce() error {
	if err := t.Type.Coerce(); err != nil {
		return err
	}
	if t.Movement == nil {
		return errors.New("Movement should not be empty")
	}
	return nil
}

// Bytes creates the byte array.
func (t *Actor) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
