// This file was generated by typhen-api

package battle

import (
	"errors"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi"
)

var _ = errors.New

// Actor is a kind of TyphenAPI type.
type Actor struct {
	Id        int64                 `json:"id" msgpack:"id"`
	UserId    int64                 `json:"user_id" msgpack:"user_id"`
	Type      ActorType             `json:"type" msgpack:"type"`
	Movement  *Movement             `json:"movement" msgpack:"movement"`
	IsVisible bool                  `json:"is_visible" msgpack:"is_visible"`
	Submarine *ActorSubmarineObject `json:"submarine" msgpack:"submarine"`
}

// Coerce the fields.
func (t *Actor) Coerce() error {
	if err := t.Type.Coerce(); err != nil {
		return err
	}
	if t.Movement == nil {
		return errors.New("Movement should not be empty")
	}
	return nil
}

// Bytes creates the byte array.
func (t *Actor) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
