// This file was generated by typhen-api

package battle

import (
	"errors"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi/core"
)

var _ = errors.New

// ActorSubmarineObject is a kind of TyphenAPI type.
type ActorSubmarineObject struct {
	Equipment     *Equipment `codec:"equipment"`
	IsUsingPinger bool       `codec:"is_using_pinger"`
}

// Coerce the fields.
func (t *ActorSubmarineObject) Coerce() error {
	if t.Equipment == nil {
		return errors.New("Equipment should not be empty")
	}
	return nil
}

// Bytes creates the byte array.
func (t *ActorSubmarineObject) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
