// This file was generated by typhen-api

package battle

import (
	"errors"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi"
)

var _ = errors.New

// EquipmentItem is a kind of TyphenAPI type.
type EquipmentItem struct {
	CooldownStartedAt int64 `json:"cooldown_started_at" msgpack:"cooldown_started_at"`
	CooldownDuration  int64 `json:"cooldown_duration" msgpack:"cooldown_duration"`
}

// Coerce the fields.
func (t *EquipmentItem) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *EquipmentItem) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
