// This file was generated by typhen-api

package battle

import (
	"errors"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi/core"
)

var _ = errors.New

// Movement is a kind of TyphenAPI type.
type Movement struct {
	ActorId     int64        `codec:"actor_id"`
	Position    *Point       `codec:"position"`
	Direction   float64      `codec:"direction"`
	MovedAt     int64        `codec:"moved_at"`
	Accelerator *Accelerator `codec:"accelerator"`
}

// Coerce the fields.
func (t *Movement) Coerce() error {
	if t.Position == nil {
		return errors.New("Position should not be empty")
	}
	return nil
}

// Bytes creates the byte array.
func (t *Movement) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
