// This file was generated by typhen-api

package battle

import (
	"errors"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi"
)

var _ = errors.New

// RoomMember is a kind of TyphenAPI type.
type RoomMember struct {
	Id     int64  `json:"id" msgpack:"id"`
	RoomId int64  `json:"room_id" msgpack:"room_id"`
	Name   string `json:"name" msgpack:"name"`
}

// Coerce the fields.
func (t *RoomMember) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *RoomMember) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
