// This file was generated by typhen-api

package battle

import (
	"errors"
	"github.com/shiwano/submarine/server/battle/lib/typhenapi/core"
)

var _ = errors.New

// Room is a kind of TyphenAPI type.
type Room struct {
	Id int64 `codec:"id"`
}

// Coerce the fields.
func (t *Room) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *Room) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
