// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// Config is kind of a TyphenAPI type.
type Config struct {
	Version             string `codec:"version"`
	WebApiServerBaseUri string `codec:"web_api_server_base_uri"`
}

// Coerce the fields.
func (t *Config) Coerce() error {
	return nil
}
