// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// CreateRoomObject is kind of a TyphenAPI type.
type CreateRoomObject struct {
	Room *Room `codec:"room"`
}

// Coerce the fields.
func (t *CreateRoomObject) Coerce() error {
	if t.Room == nil {
		return errors.New("Room should not be empty")
	}
	return nil
}
