// This file was generated by typhen-api

package submarine

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// FindUserObject is a kind of TyphenAPI type.
type FindUserObject struct {
	User *User `codec:"user"`
}

// Coerce the fields.
func (t *FindUserObject) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *FindUserObject) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
