// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// FindUserObject is kind of a TyphenAPI type.
type FindUserObject struct {
	User *User `codec:"user"`
}

// Coerce the fields.
func (t *FindUserObject) Coerce() error {
	return nil
}
