// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// GetRoomsObject is kind of a TyphenAPI type.
type GetRoomsObject struct {
	Rooms []Room `codec:"rooms"`
}

// Coerce the fields.
func (t *GetRoomsObject) Coerce() error {
	if t.Rooms == nil {
		return errors.New("Rooms should not be empty")
	}
	return nil
}
