// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// JoinedRoom is kind of a TyphenAPI type.
type JoinedRoom struct {
	BattleServerBaseUri string `codec:"battle_server_base_uri"`
	RoomKey             string `codec:"room_key"`
	Id                  int    `codec:"id"`
	Members             []User `codec:"members"`
}

// Coerce the fields.
func (t *JoinedRoom) Coerce() error {
	if t.Members == nil {
		return errors.New("Members should not be empty")
	}
	return nil
}
