// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// JoinIntoRoomObject is kind of a TyphenAPI type.
type JoinIntoRoomObject struct {
	RoomKey string `codec:"room_key"`
}

// Coerce the fields.
func (t *JoinIntoRoomObject) Coerce() error {
	return nil
}
