// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// JoinIntoRoomObject is kind of a TyphenAPI type.
type JoinIntoRoomObject struct {
	Room *JoinedRoom `codec:"room"`
}

// Coerce the fields.
func (t *JoinIntoRoomObject) Coerce() error {
	if t.Room == nil {
		return errors.New("Room should not be empty")
	}
	return nil
}
