// This file was generated by typhen-api

package submarine

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// JoinIntoRoomObject is a kind of TyphenAPI type.
type JoinIntoRoomObject struct {
	Room *JoinedRoom `codec:"room"`
}

// Coerce the fields.
func (t *JoinIntoRoomObject) Coerce() error {
	if t.Room == nil {
		return errors.New("Room should not be empty")
	}
	return nil
}

// Bytes creates the byte array.
func (t *JoinIntoRoomObject) Bytes(serializer *typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
