// This file was generated by typhen-api

package submarine

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// LoggedInUser is a kind of TyphenAPI type.
type LoggedInUser struct {
	JoinedRoom *JoinedRoom `codec:"joined_room"`
	Id         int64       `codec:"id"`
	Name       string      `codec:"name"`
}

// Coerce the fields.
func (t *LoggedInUser) Coerce() error {
	return nil
}

// Bytes creates the byte array.
func (t *LoggedInUser) Bytes(serializer typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
