// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// LoggedInUser is kind of a TyphenAPI type.
type LoggedInUser struct {
	JoinedRoom *JoinedRoom `codec:"joined_room"`
	Name       string      `codec:"name"`
}

// Coerce the fields.
func (t *LoggedInUser) Coerce() error {
	return nil
}
