// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// Room is kind of a TyphenAPI type.
type Room struct {
	Id                  int    `codec:"id"`
	BattleServerBaseUri string `codec:"battle_server_base_uri"`
	Members             []User `codec:"members"`
}

// Coerce the fields.
func (t *Room) Coerce() error {
	if t.Members == nil {
		return errors.New("Members should not be empty")
	}
	return nil
}
