// This file was generated by typhen-api

package submarine

import (
	"app/typhenapi/core"
	"errors"
)

var _ = errors.New

// SignUpObject is a kind of TyphenAPI type.
type SignUpObject struct {
	User *LoggedInUser `codec:"user"`
}

// Coerce the fields.
func (t *SignUpObject) Coerce() error {
	if t.User == nil {
		return errors.New("User should not be empty")
	}
	return nil
}

// Bytes creates the byte array.
func (t *SignUpObject) Bytes(serializer *typhenapi.Serializer) ([]byte, error) {
	if err := t.Coerce(); err != nil {
		return nil, err
	}

	data, err := serializer.Serialize(t)
	if err != nil {
		return nil, err
	}

	return data, nil
}
