// This file was generated by typhen-api

package submarine

import (
	"errors"
)

var _ = errors.New

// User is kind of a TyphenAPI type.
type User struct {
	Name string `codec:"name"`
}

// Coerce the fields.
func (t *User) Coerce() error {
	return nil
}
