// This file was generated by typhen-api

package battle

import (
	"errors"
)

var _ = errors.New

// Ping is kind of a TyphenAPI type.
type Ping struct {
	Message string `codec:"message"`
}

// Coerce the fields.
func (t *Ping) Coerce() error {
	return nil
}

// RealTimeMessageType returns the real time message type.
func (t *Ping) RealTimeMessageType() int32 {
	return -973977363
}
