# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class Accelerator
    include Virtus.model(:strict => true)

    attribute :max_speed, Number, :required => true
    attribute :duration, Integer, :required => true
    attribute :start_rate, Number, :required => true
    attribute :is_accelerating, Boolean, :required => true
    attribute :changed_at, Integer, :required => true
  end
end
