# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class Actor
    include Virtus.model(:strict => true)

    attribute :id, Integer, :required => true
    attribute :user_id, Integer, :required => true
    attribute :type, TyphenApi::Model::Submarine::Battle::ActorType, :required => true
    attribute :movement, TyphenApi::Model::Submarine::Battle::Movement, :required => true
    attribute :is_visible, Boolean, :required => true
  end
end
