# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class ActorRequestObject
    include Virtus.model(:strict => true)

    attribute :type, TyphenApi::Model::Submarine::Battle::ActorType, :required => true
  end
end
