# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class Actor
    include Virtus.model(:strict => true)

    attribute :id, Integer, :required => true
    attribute :user_id, Integer, :required => true
    attribute :type, TyphenApi::Model::Submarine::Battle::ActorType, :required => true
    attribute :position, TyphenApi::Model::Submarine::Battle::Vector, :required => true
  end
end
