# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class Destruction
    include Virtus.model(:strict => true)

    attribute :actor_id, Integer, :required => true
  end
end
