# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class EquipmentItem
    include Virtus.model(:strict => true)

    attribute :cooldown_started_at, Integer, :required => true
    attribute :cooldown_duration, Integer, :required => true
  end
end
