# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class Equipment
    include Virtus.model(:strict => true)

    attribute :actor_id, Integer, :required => true
    attribute :torpedos, Array[TyphenApi::Model::Submarine::Battle::EquipmentItem], :required => true
    attribute :pinger, TyphenApi::Model::Submarine::Battle::EquipmentItem, :required => true
    attribute :watcher, TyphenApi::Model::Submarine::Battle::EquipmentItem, :required => true
  end
end
