# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class FindRoomObject
    include Virtus.model(:strict => true)

    attribute :room, TyphenApi::Model::Submarine::Battle::Room, :required => false
  end
end
