# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class Finish
    include Virtus.model(:strict => true)

    attribute :winner_user_id, Integer, :required => false
    attribute :finished_at, Integer, :required => true
  end
end
