# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class Movement
    include Virtus.model(:strict => true)

    attribute :actor_id, Integer, :required => true
    attribute :position, TyphenApi::Model::Submarine::Battle::Vector, :required => true
    attribute :velocity, TyphenApi::Model::Submarine::Battle::Vector, :required => true
    attribute :moved_at, Integer, :required => true
  end
end
