# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class NowObject
    include Virtus.model(:strict => true)

    attribute :time, Integer, :required => true
  end
end
