# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class Pinger
    include Virtus.model(:strict => true)

    attribute :actor_id, Integer, :required => true
    attribute :is_finished, Boolean, :required => true
  end
end
