# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class PlayableRoom
    include Virtus.model(:strict => true)

    attribute :id, Integer, :required => true
  end
end
