# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class RemoveBotRequest
    include Virtus.model(:strict => true)

    attribute :bot_id, Integer, :required => true
  end
end
