# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class Room
    include Virtus.model(:strict => true)

    attribute :id, Integer, :required => true
    attribute :members, Array[RoomMember], :required => true
  end
end
