# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class RoomMember
    include Virtus.model(:strict => true)

    attribute :room_key, String, :required => true
    attribute :user, TyphenApi::Model::Submarine::User, :required => true
  end
end
