# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class Start
    include Virtus.model(:strict => true)

    attribute :started_at, Integer, :required => true
  end
end
