# This file was generated by typhen-api

module TyphenApi::Model::Submarine::Battle
  class Visibility
    include Virtus.model(:strict => true)

    attribute :actor_id, Integer, :required => true
    attribute :is_visible, Boolean, :required => true
    attribute :movement, TyphenApi::Model::Submarine::Battle::Movement, :required => true
  end
end
