# This file was generated by typhen-api

require 'spec_helper'

RSpec.describe 'Generated routing by typhen-api', :type => :routing do
  it 'routes /ping to ping#service' do
    expect(:post => 'ping').to route_to(controller: 'ping', action: 'service')
  end
  it 'routes /sign_up to sign_up#service' do
    expect(:post => 'sign_up').to route_to(controller: 'sign_up', action: 'service')
  end
  it 'routes /login to login#service' do
    expect(:post => 'login').to route_to(controller: 'login', action: 'service')
  end
  it 'routes /find_user to find_user#service' do
    expect(:post => 'find_user').to route_to(controller: 'find_user', action: 'service')
  end
  it 'routes /create_room to create_room#service' do
    expect(:post => 'create_room').to route_to(controller: 'create_room', action: 'service')
  end
  it 'routes /get_rooms to get_rooms#service' do
    expect(:post => 'get_rooms').to route_to(controller: 'get_rooms', action: 'service')
  end
  it 'routes /join_into_room to join_into_room#service' do
    expect(:post => 'join_into_room').to route_to(controller: 'join_into_room', action: 'service')
  end
  it 'routes /battle/find_room to battle/find_room#service' do
    expect(:post => 'battle/find_room').to route_to(controller: 'battle/find_room', action: 'service')
  end
  it 'routes /battle/find_room_member to battle/find_room_member#service' do
    expect(:post => 'battle/find_room_member').to route_to(controller: 'battle/find_room_member', action: 'service')
  end
  it 'routes /battle/close_room to battle/close_room#service' do
    expect(:post => 'battle/close_room').to route_to(controller: 'battle/close_room', action: 'service')
  end
end
